### PR TITLE
Added line graph

### PR DESCRIPTION
**Pull request by anoninthekop**

### CODE REVIEW

**Comment by VulcanWM** [comment]
this is really nice, thanks!
apply to the bounty and send me your replit username, and i'll send over those cycles

**Review by VulcanWM — COMMENTED** [review]
amazing, just what i wanted

**Comment by anoninthekop** [comment]
Thanks. I already applied on replit. My username is @AhnafBin3

**Comment by VulcanWM** [comment]
your username doesn't show in the applications?

**Comment by anoninthekop** [comment]
I already applied but it's not showing now maybe because it is my first bounty. I have applied again and it's now under review.

**Comment by VulcanWM** [comment]
ah okay, i'll wait for it to show up then

**Comment by anoninthekop** [comment]
My application is showing on replit now

**Comment by VulcanWM** [comment]
okay just submit an empty repl and i'll accept it

**Pull request merged**
